// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOotRaNezzUm32ZM6G2QRuVUbCkoSoC-s',
    appId: '1:722278860095:web:6d585277d4ac3d11ac3f8a',
    messagingSenderId: '722278860095',
    projectId: 'petcare-5d350',
    authDomain: 'petcare-5d350.firebaseapp.com',
    databaseURL: 'https://petcare-5d350-default-rtdb.firebaseio.com',
    storageBucket: 'petcare-5d350.appspot.com',
    measurementId: 'G-HMVGMKC5SZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATTcWnpof-9RpOD0NN-fdg1YnvbVAwfPY',
    appId: '1:722278860095:android:22df2faad8776cb0ac3f8a',
    messagingSenderId: '722278860095',
    projectId: 'petcare-5d350',
    databaseURL: 'https://petcare-5d350-default-rtdb.firebaseio.com',
    storageBucket: 'petcare-5d350.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlZbmajwpCPHcSOzPbxjWZIc3F1KMaVus',
    appId: '1:722278860095:ios:1b0ac81ae1a452feac3f8a',
    messagingSenderId: '722278860095',
    projectId: 'petcare-5d350',
    databaseURL: 'https://petcare-5d350-default-rtdb.firebaseio.com',
    storageBucket: 'petcare-5d350.appspot.com',
    iosClientId: '722278860095-i27894m0p4b9frl2me7v02jjemb394pg.apps.googleusercontent.com',
    iosBundleId: 'com.example.petcare',
  );
}
